"""Uninstall helpers — per-surface export to default locations.

User-clarification (2026-06-06): `uninstall` should offer a
data-restore step that can write back to default file/format
locations for memory, kanban, wiki, sessions, metrics. This
module implements the default-location mapping.

Default locations per surface:
  memory   → ~/.hermes/memories/MEMORY.md   (markdown bullet list)
  kanban   → ~/.hermes/kanban/boards/<tenant>/kanban.db  (SQLite)
  wiki     → ~/.hermes/wiki/<slug>.md       (per-slug markdown)
  sessions → ~/.hermes/sessions/YYYY-MM-DD/*.jsonl
  metrics  → ~/.hermes/metrics/events.jsonl
  journal  → ~/.hermes/journal/<sid>.jsonl
  skills   → ~/.hermes/skills/index.json
"""

from __future__ import annotations

import json
import os
from collections.abc import Iterable
from pathlib import Path

from hermes_memory import __version__ as _version  # noqa: F401  (used in export envelope)

HERMES_HOME = Path(os.environ.get("HERMES_HOME", "~/.hermes")).expanduser()


def _repo_or_none(name: str):
    """Return the active repo for `name`, or None if not wired."""
    try:
        from hermes_memory.pg_repos import (
            PgJournalRepo,
            PgKanbanRepo,
            PgMemoryRepo,
            PgMetricsRepo,
            PgSessionsRepo,
            PgSkillsRepo,
            PgWikiRepo,
        )
        dsn = os.environ.get("HERMES_PG_CONN_STR")
        if not dsn:
            return None
        mapping = {
            "memory": PgMemoryRepo,
            "wiki": PgWikiRepo,
            "kanban": PgKanbanRepo,
            "sessions": PgSessionsRepo,
            "metrics": PgMetricsRepo,
            "journal": PgJournalRepo,
            "skills": PgSkillsRepo,
        }
        cls = mapping.get(name)
        if cls is None:
            return None
        return cls(dsn)
    except Exception:  # noqa: BLE001
        return None


def _write_default_locations() -> dict[str, Path]:
    return {
        "memory": HERMES_HOME / "memories" / "MEMORY.md",
        "kanban": HERMES_HOME / "kanban",
        "wiki": HERMES_HOME / "wiki",
        "sessions": HERMES_HOME / "sessions",
        "metrics": HERMES_HOME / "metrics" / "events.jsonl",
        "journal": HERMES_HOME / "journal",
        "skills": HERMES_HOME / "skills" / "index.json",
    }


# ---------------------------------------------------------------------------
# memory → markdown
# ---------------------------------------------------------------------------
def export_memory_to_markdown(path: Path) -> int:
    """Dump memories as a markdown bullet list. Returns count written."""
    repo = _repo_or_none("memory")
    path.parent.mkdir(parents=True, exist_ok=True)
    if repo is None:
        path.write_text(
            f"# MEMORY.md (rollback stub)\n\n"
            f"_No postgres connection. Generated by hermes-memory v{_version}._\n"
        )
        return 0
    # We don't have a "list all" method on the base repo; use search
    # with an empty-ish query is also broken. Use a direct PG fetch.
    try:
        import psycopg  # noqa: F401
    except ImportError:
        path.write_text("# MEMORY.md\n\n_psycopg3 not installed._\n")
        return 0
    dsn = os.environ.get("HERMES_PG_CONN_STR", "")
    with psycopg.connect(dsn) as c:  # noqa: F841
        with c.cursor() as cur:
            cur.execute(
                "SELECT id, content, tags, category, source, created_at "
                "FROM agent_memory.memories "
                "WHERE deleted_at IS NULL "
                "ORDER BY created_at DESC"
            )
            rows = cur.fetchall()
    lines = ["# MEMORY.md", ""]
    for r in rows:
        mid, content, tags, category, source, ts = r
        meta_bits = []
        if category:
            meta_bits.append(f"`{category}`")
        if tags:
            meta_bits.append(", ".join(f"`{t}`" for t in tags))
        if source:
            meta_bits.append(f"source: `{source}`")
        meta = " — " + " · ".join(meta_bits) if meta_bits else ""
        lines.append(f"- {content}{meta}")
    path.write_text("\n".join(lines) + "\n")
    return len(rows)


# ---------------------------------------------------------------------------
# wiki → per-slug markdown
# ---------------------------------------------------------------------------
def export_wiki_to_markdown(out_dir: Path) -> int:
    repo = _repo_or_none("wiki")
    out_dir.mkdir(parents=True, exist_ok=True)
    if repo is None:
        return 0
    try:
        import psycopg
    except ImportError:
        return 0
    dsn = os.environ.get("HERMES_PG_CONN_STR", "")
    with psycopg.connect(dsn) as c:
        with c.cursor() as cur:
            cur.execute(
                "SELECT slug, title, body_md, category, metadata, updated_at "
                "FROM hermes_wiki.documents ORDER BY slug"
            )
            rows = cur.fetchall()
    n = 0
    for slug, title, body, category, metadata, _ts in rows:
        front = ["---", f"title: {title}", f"slug: {slug}"]
        if category:
            front.append(f"category: {category}")
        if metadata:
            front.append(f"metadata: {json.dumps(metadata)}")
        front.append("---\n")
        (out_dir / f"{slug}.md").write_text("\n".join(front) + body + "\n")
        n += 1
    return n


# ---------------------------------------------------------------------------
# sessions → per-day jsonl
# ---------------------------------------------------------------------------
def export_sessions_to_jsonl(out_dir: Path) -> int:
    repo = _repo_or_none("sessions")
    out_dir.mkdir(parents=True, exist_ok=True)
    if repo is None:
        return 0
    try:
        import psycopg
    except ImportError:
        return 0
    dsn = os.environ.get("HERMES_PG_CONN_STR", "")
    n = 0
    with psycopg.connect(dsn) as c:
        with c.cursor() as cur:
            cur.execute(
                "SELECT id, profile, started_at, ended_at, metadata "
                "FROM hermes_journal.sessions ORDER BY started_at"
            )
            sessions = cur.fetchall()
            for sid, profile, started, ended, metadata in sessions:
                day = started.strftime("%Y-%m-%d")
                (out_dir / day).mkdir(parents=True, exist_ok=True)
                f = out_dir / day / f"session_{sid}.jsonl"
                envelope = {
                    "session_id": sid,
                    "profile": profile,
                    "started_at": str(started),
                    "ended_at": str(ended) if ended else None,
                    "metadata": metadata,
                }
                with f.open("w") as out:
                    out.write(json.dumps(envelope) + "\n")
                    cur.execute(
                        "SELECT role, content, tool_calls, ts "
                        "FROM hermes_journal.messages "
                        "WHERE session_id = %s ORDER BY ts",
                        (sid,),
                    )
                    for role, content, tool_calls, ts in cur.fetchall():
                        out.write(json.dumps({
                            "role": role,
                            "content": content,
                            "tool_calls": tool_calls,
                            "ts": str(ts),
                        }) + "\n")
                n += 1
    return n


# ---------------------------------------------------------------------------
# metrics → jsonl
# ---------------------------------------------------------------------------
def export_metrics_to_jsonl(path: Path) -> int:
    repo = _repo_or_none("metrics")
    path.parent.mkdir(parents=True, exist_ok=True)
    if repo is None:
        path.write_text("")
        return 0
    try:
        import psycopg
    except ImportError:
        path.write_text("")
        return 0
    dsn = os.environ.get("HERMES_PG_CONN_STR", "")
    with psycopg.connect(dsn) as c:
        with c.cursor() as cur:
            cur.execute(
                "SELECT profile, name, value, tags, ts "
                "FROM hermes_metrics.events ORDER BY ts"
            )
            rows = cur.fetchall()
    with path.open("w") as f:
        for profile, name, value, tags, ts in rows:
            f.write(json.dumps({
                "profile": profile, "name": name, "value": value,
                "tags": tags, "ts": str(ts),
            }) + "\n")
    return len(rows)


# ---------------------------------------------------------------------------
# kanban → SQLite (best-effort; full impl in v2.1)
# ---------------------------------------------------------------------------
def export_kanban_to_sqlite(out_dir: Path) -> int:
    """Stub: v2.0 writes a JSON manifest per tenant. SQLite export lands in v2.1."""
    out_dir.mkdir(parents=True, exist_ok=True)
    repo = _repo_or_none("kanban")
    if repo is None:
        return 0
    try:
        import psycopg
    except ImportError:
        return 0
    dsn = os.environ.get("HERMES_PG_CONN_STR", "")
    with psycopg.connect(dsn) as c:
        with c.cursor() as cur:
            cur.execute("SELECT id, slug, name, description FROM hermes_kanban.tenants")
            tenants = cur.fetchall()
    n = 0
    for tid, slug, name, description in tenants:
        tenant_dir = out_dir / "boards" / slug
        tenant_dir.mkdir(parents=True, exist_ok=True)
        # JSON manifest as a stand-in for SQLite (v2.1 fills this)
        (tenant_dir / "kanban.json").write_text(json.dumps({
            "tenant_id": tid, "name": name, "description": description,
            "note": "v2.0 stub — full SQLite export in v2.1",
        }, indent=2))
        n += 1
    return n


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------
def export_surfaces(surfaces: Iterable[str]) -> dict[str, int]:
    """Export each surface in `surfaces` to its default location.
    Returns a {surface: count} dict.
    """
    locations = _write_default_locations()
    out: dict[str, int] = {}
    for s in surfaces:
        if s == "memory":
            out[s] = export_memory_to_markdown(locations["memory"])
        elif s == "wiki":
            out[s] = export_wiki_to_markdown(locations["wiki"])
        elif s == "sessions":
            out[s] = export_sessions_to_jsonl(locations["sessions"])
        elif s == "metrics":
            out[s] = export_metrics_to_jsonl(locations["metrics"])
        elif s == "kanban":
            out[s] = export_kanban_to_sqlite(locations["kanban"])
        else:
            out[s] = 0  # journal / skills deferred
    for s, n in out.items():
        print(f"    {s}: {n} record(s) exported")
    return out
